#!/bin/sh

set -e

cur_dir=$(dirname -- "$(realpath "$0")")

ln -f -s "$cur_dir"/gitconfig "$HOME"/.gitconfig

ln -f -s "$cur_dir"/digrc "$HOME"/.digrc

ln -f -s "$cur_dir/vim" "$HOME/.vim"

mkdir -p "$HOME/.config/fish/functions"
mkdir -p "$HOME/.config/fish/themes"
ln -f -s "$cur_dir/fish/config.fish" "$HOME/.config/fish/config.fish"
for file in "$cur_dir"/fish/functions/*; do
	ln -f -s "$file" "$HOME/.config/fish/functions/${file##*/}"
done

ln -f -s "$cur_dir"/zshrc "$HOME/.zshrc"

ln -f -s "$cur_dir"/tmux.conf "$HOME/.tmux.conf"
