set nocompatible           " be iMproved
filetype off

"" General configuration
filetype plugin indent on
syntax on
set encoding=utf-8
set termencoding=utf-8

" Automatic reloading of .vimrc
autocmd! bufwritepost .vimrc source %

"
" Color scheme 
" Get Mac Terminal Colors from:
" https://github.com/tomislav/osx-terminal.app-colors-solarized
" Get Elementary OS colors from:
" https://gist.github.com/matiasleidemer/24a32d80e8409984557e
" Get Ubuntu Gnome Terminal colors from:
" https://github.com/Anthony25/gnome-terminal-colors-solarized
set t_Co=256
set background=dark
"colorscheme solarized


" Mouse and backspace
set mouse=a  " on OSX press ALT and click
set bs=2     " make backspace behave like normal again
" Allow using backspace and del keys for indentations, lineendings and
" linestarts
set backspace=indent,eol,start

" Showing line numbers and length
set number  " show line numbers
set nowrap  " don't automatically wrap on load
set fo-=t   " don't automatically wrap text when typing

" Useful settings
set history=700
set undolevels=700

function! UseTabs()
  set tabstop=4     " Size of a hard tabstop (ts).
  set shiftwidth=4  " Size of an indentation (sw).
  set noexpandtab   " Always uses tabs instead of space characters (noet).
  set autoindent    " Copy indent from current line when starting a new line (ai).
endfunction

function! UseSpaces()
  set tabstop=2     " Size of a hard tabstop (ts).
  set shiftwidth=2  " Size of an indentation (sw).
  set expandtab     " Always uses spaces instead of tab characters (et).
  set softtabstop=2 " Number of spaces a <Tab> counts for. When 0, featuer is off (sts).
  set autoindent    " Copy indent from current line when starting a new line.
  set smarttab      " Inserts blanks on a <Tab> key (as per sw, ts and sts).
endfunction

" By default, use tabs
call UseTabs()


" Searching
set hlsearch        " highlight matches
set incsearch       " incremental searching
set ignorecase      " searches are case insensitive...
set smartcase       " ... unless they contain at least one capital letter

" Disable backup and swap files - they trigger too many events
" for file system watchers
set nobackup
set nowritebackup
set noswapfile

" Rebind <Leader> key
" I like to have it here becuase it is easier to reach than the default and
" it is next to ``m`` and ``n`` which I use for navigating between tabs.
let mapleader = ","

" Copy to clipboard for Mac
map <leader>c :w !pbcopy<CR><CR>

" Bind nohl
" Removes highlight of your last search
" ``<C>`` stands for ``CTRL`` and therefore ``<C-n>`` stands for ``CTRL+n``
"noremap <C-n> :nohl<CR>
"vnoremap <C-n> :nohl<CR>
"inoremap <C-n> :nohl<CR>

" bind Ctrl+<movement> keys to move around the windows, instead of using Ctrl+w + <movement>
" Every unnecessary keystroke that can be saved is good for your health :)
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h


" easier moving between tabs
map <Leader>n <esc>:tabprevious<CR>
map <Leader>m <esc>:tabnext<CR>


" easier moving of code blocks
" Try to go into visual mode (v), thenselect several lines of code here and
" then press ``>`` several times.
vnoremap < <gv  " better indentation
vnoremap > >gv  " better indentation

" Powerline
" NOTE: You can install a font and configure the terminal to use it
" I prefer DejavuSansMono 
" https://github.com/Lokaltog/powerline-fonts
set laststatus=2
let g:Powerline_symbols='fancy'
set fillchars+=stl:\ ,stlnc:\
